name = "purple-fireflies-website"
main = ".open-next/worker.js"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "purple_fireflies_db"
database_name = "purple-fireflies-db"
database_id = "295c9661-624c-4964-8d1f-69f6c991a4f0"

[[kv_namespaces]]
binding = "CACHE"
id = "c7014b56c6d343e8a223d8a41d034731"

[env.preview]
name = "purple-fireflies-website-preview"
workers_dev = true

[[env.preview.d1_databases]]
binding = "purple_fireflies_db"
database_name = "purple-fireflies-db"
database_id = "dcb6e0de-2d20-40bc-82c3-1ccd96f0a540"

[[env.preview.kv_namespaces]]
binding = "CACHE"
id = "daaa882613904099a98253c927a86f08"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
