name = "purple-fireflies-website"
main = ".open-next/worker.js"
compatibility_date = "2026-04-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "purple-fireflies-db"
database_id = ""

# [[kv_namespaces]]
# binding = "CACHE"
# id = ""
# preview_id = ""
